
spring:
  data:
    rest:
      base-path: /api

multipart:
  max-request-size: 50MB
  max-file-size: 50MB

ruleset:
  rules:
    web.xml:  application has web xml
    ejb: application has an ejb file
